spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/football?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: s814466057
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.echo.service.pojo
  mapper-locations: classpath:mybatis/mappers/**/*.xml
